config/routes.rb
SampleApp::Application.routes.draw do

  root :to => 'static_pages#home'

  match '/signup', :to => 'users#new'

  match '/help', :to => 'static_pages#help'
  match '/contact', :to => 'static_pages#contact'
  match '/about', :to => 'static_pages#about'

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessible :name, :email, :password, :password_confirmation
    has_secure_password

    before_save { |user| user.email = user.email.downcase }

    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    validates :password, presence: true, length: { minimum: 6 }

    validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on the per-page basis.
def full_title(page_title)
    base_title = "New Application"
    if page_title.empty?
        base_title
    else
        "#{base_title} | #{page_title}"
    end
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_foot.html.erb
    <div id="footer">
        <div class="container">
            <div id="pushfooter"></div>
    <small>
        A footer customed by @Gizem, 2013
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org">News</a></li>
        </ul>
    </nav>
</div>
    </div>

app/views/layouts/_head.html.erb
<div class="container">
      <div class="masthead">
        <h3 class="muted"><%= link_to "sample app", root_path, id: "logo" %></h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <li><%= link_to "Sign in", '#' %></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<div id="wrap">
    <%= render 'layouts/head' %>
    <%= yield %>
    </div>
    <div id="push"></div>
</div>

<%= render 'layouts/foot' %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>


<h1>About</h1>
    <p>New Sample Page about the Application</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact Page</h1>
    <p>Contact with me, grgizem@gmail.com</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help Page</h1>
    <p>Welcome to the new help page!</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<div class="jumbotron">
<h1>Home Page</h1>
<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
<%= link_to "Get started today!", signup_path, class: "btn btn-large btn-success" %>
</div>
</div>
<hr>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>

<h1>Signup</h1>
<p>Find me in app/views/users/new.html.erb</p>